### ISSUE TITLE
ProgrammingError

### ISSUE THREAD

**Issue by Maho91** [aristotle-mdr/aristotle-mdr.github.io#2]
I installed Aristotle MDR and I am exploring it, however, the app is full of programming errors, e.g. null exceptions and select data errors. Also when I try to create some object or data type the page keeps loading with no response. I am wondering why is the app full of errors? 
I did the installation using pip3 correctly with Django migration also I used Postgres database. 

Any help please, thank you in advance

**Comment by LegoStormtroopr** [comment]
Hi @Maho91 . Unfortunately, at this stage have chosen to suspend releasing the Aristotle MDR source code as open source.
So I'm not sure what version you are currently using which will make it hard to diagnose.

We do offer a professionally supported SaaS version of Aristotle. If you are interested, please contact us a hello@aristotlemetadata.com
